db:
  image: mysql:5.7.17
  environment:
    MYSQL_DATABASE: brainstorm
    MYSQL_ROOT_PASSWORD: secret

web:
  tty: true
  stdin_open: true
  build: .
  volumes:
    - .:/root/brainstorm
  ports:
    - 3000:3000
  links:
    - db
  environment:
    RAILS_ENV: development
    DISABLE_SPRING: 'true'
    DB_HOST: db
    DB_PORT: 3306
    DB_NAME: brainstorm
    DB_USER: root
    DB_PASSWORD: secret
