default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: brainstorm_test

production:
  <<: *default
