# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d94cc1dc4e9ff2fe9b39e34d67f602b06b36d1982bb550a689057335c354cb659e387fa6ef6dc20b1223bd8f862ee26430bf69e420c0e6ff1068bfaafc5aa56

test:
  secret_key_base: 83b8c18acd77174c4b0ed7a247b6f835cc6480b2a5c48f6e9f8c3099051bab0872729fe04d6469d4e408304433d84832f32a868ede4a21d57be3cb13b5d58847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
